/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrpcSplatRouteImport } from './routes/trpc.$'
import { Route as ApiCronRouteImport } from './routes/api.cron'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrpcSplatRoute = TrpcSplatRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/trpc/$': typeof TrpcSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cron' | '/trpc/$' | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cron' | '/trpc/$' | '/api/v1/$'
  id: '__root__' | '/' | '/api/cron' | '/trpc/$' | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCronRoute: typeof ApiCronRoute
  TrpcSplatRoute: typeof TrpcSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCronRoute: ApiCronRoute,
  TrpcSplatRoute: TrpcSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
